### ISSUE TITLE
Gutenpack feature stopped working due to missing dependancies

### ISSUE THREAD

**Issue by brbrr** [Automattic/jurassic.ninja#148]
Calypso recently added `weak` dependency (https://github.com/Automattic/wp-calypso/pull/28875) which needs to be build, but JN sites missing `make` command. So any gutenpack sites are failing to build. 

Full error log: 

```
-> Getting wp-calypso branch master
-> Cloning into 'wp-calypso'...
-> -> > fsevents@1.2.4 install /srv/users/user9b0aae60/wp-calypso/node_modules/chokidar/node_modules/fsevents
-> > node install
-> ->
-> > node-sass@4.10.0 install /srv/users/user9b0aae60/wp-calypso/node_modules/node-sass
-> > node scripts/install.js
-> -> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-64_binding.node
-> Download complete
-> Binary saved to /srv/users/user9b0aae60/wp-calypso/node_modules/node-sass/vendor/linux-x64-64/binding.node
-> Caching binary to /srv/users/user9b0aae60/.npm/node-sass/4.10.0/linux-x64-64_binding.node
-> -> > node-sass@4.10.0 postinstall /srv/users/user9b0aae60/wp-calypso/node_modules/node-sass
-> > node scripts/build.js
-> -> Binary found at /srv/users/user9b0aae60/wp-calypso/node_modules/node-sass/vendor/linux-x64-64/binding.node
-> Testing binary
-> Binary is fine
-> -> > fsevents@2.0.1 install /srv/users/user9b0aae60/wp-calypso/node_modules/fsevents
-> > [ -f fsevents.node ] || npm run prepare
-> ->
-> > weak@1.0.1 install /srv/users/user9b0aae60/wp-calypso/node_modules/weak
-> > node-gyp rebuild
-> -> gyp ERR! build error
-> gyp ERR! stack Error: not found: make
-> gyp ERR! stack at getNotFoundError (/srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:13:12)
-> gyp ERR! stack at F (/srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:68:19)
-> gyp ERR! stack at E (/srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:80:29)
-> gyp ERR! stack at /srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/which/which.js:89:16
-> gyp ERR! stack at /srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/isexe/index.js:42:5
-> gyp ERR! stack at /srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
-> gyp ERR! stack at FSReqWrap.oncomplete (fs.js:154:21)
-> gyp ERR! System Linux 4.4.0-135-generic
-> gyp ERR! command "/srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/bin/node" "/srv/users/user9b0aae60/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
-> gyp ERR! cwd /srv/users/user9b0aae60/wp-calypso/node_modules/weak
-> gyp ERR! node -v v10.14.1
-> gyp ERR! node-gyp -v v3.8.0
-> gyp ERR! not ok
-> npm ERR! code ELIFECYCLE
-> npm ERR! errno 1
-> npm ERR! weak@1.0.1 install: `node-gyp rebuild`
-> npm ERR! Exit status 1
-> npm ERR!
-> npm ERR! Failed at the weak@1.0.1 install script.
-> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
-> -> npm ERR! A complete log of this run can be found in:
-> npm ERR! /srv/users/user9b0aae60/.npm/_logs/2018-11-30T06_08_14_404Z-debug.log
```

`apt-get install -y build-essential` might fix the problem, but unfortunately - JN user dont have root privilages, so instalation is not quite possible.

**Comment by brbrr** [comment]
It was fixed by simply installing `build-essential` apt package on DO machine as root user
