### ISSUE TITLE
Errors occurred with API when creating new site

### ISSUE THREAD

**Issue by jrick1229** [Automattic/jurassic.ninja#221]
### Issue

I was creating a new site for testing today with the following settings: https://d.pr/i/SZ6iga

I received the email that the site was created: https://d.pr/i/hTm2qA - but the error appeared at the top of the settings page:

> Oh No! There was a problem launching the new WP. (The API responded in a weird way).

When going to the site: https://solar-albatross.jurassic.ninja/ - I'm given the following error:

```
Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/users/user55123de7/apps/user55123de7/public/wp-includes/load.php on line 651

Notice: Trying to access array offset on value of type bool in /srv/users/user55123de7/apps/user55123de7/public/wp-includes/theme.php on line 2241

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/users/user55123de7/apps/user55123de7/public/wp-includes/formatting.php on line 4381

Fatal error: Uncaught Error: Call to undefined function determine_locale() in /srv/users/user55123de7/apps/user55123de7/public/wp-content/plugins/woocommerce/includes/class-woocommerce.php:609 
Stack trace: 
#0 /srv/users/user55123de7/apps/user55123de7/public/wp-content/plugins/woocommerce/includes/class-woocommerce.php(577): WooCommerce->load_plugin_textdomain() 
#1 /srv/users/user55123de7/apps/user55123de7/public/wp-includes/class-wp-hook.php(286): WooCommerce->init('') 
#2 /srv/users/user55123de7/apps/user55123de7/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#3 /srv/users/user55123de7/apps/user55123de7/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#4 /srv/users/user55123de7/apps/user55123de7/public/wp-settings.php(450): do_action('init') #5 /srv/users/user55123de7/apps/user55123de7/public/wp-config.php(80): require_once('/srv/users/user...') 
#6 /srv/users/user55123de7/apps/user55123de7/public/wp-load.php(37): require_once('/srv/users/user...') 
#7 /srv/users/user55123de7/app in /srv/users/user55123de7/apps/user55123de7/public/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 609
```

**Comment by kraftbj** [comment]
Closing this to defer to #211.
